config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'projects#index'
  resources :projects
  resources :issue_templates do
    collection do
      post :add_attribute
    end
  end
  resources :sessions
  resources :users
  resources :concrete_issue_templates do
    collection do
      post :send_to_jira
    end
  end

  post 'first_login', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/views/templates/index.html.erb
<div class="button-div">
  <%= button_to "Template erstellen", new_template_path, method: :get, class: "btn btn-info float-end mt-5" %>
</div>
<div class="table-container">
  <table id="templates-table" class="table table-hover shadow rounded-custom">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Titel</th>
<!--        <th scope="col">Erstellt</th>-->
      </tr>
    </thead>
    <tbody>
      <% @templates.each do |t| %>
        <tr>
          <th scope="row"><%= t.id %></th>
          <td><%= t.title %></td>
<!--          <td><%#= t.created_for_project? %></td>-->
        </tr>
      <% end %>
      <tr>
        <th scope="row">1</th>
        <td>Paypal</td>
<!--        <td><span class="fas fa-check"></span></td>-->
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Zahlungsoptionen</td>
<!--        <td><span class="fas fa-check"></span></td>-->
      </tr>
    </tbody>
  </table>
</div>