config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'projects#index'
  resources :projects
  resources :issue_templates do
    collection do
      post :add_attribute
    end
  end
  resources :sessions
  resources :users
  resources :concrete_issue_templates do
    collection do
      post :send_to_jira
    end
  end

  post 'first_login', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/models/project.rb
class Project < ApplicationRecord

  has_many :concrete_issue_templates
  validates :external_key, presence: true

  # def create_missing_projects(projects)
  #   projects.each do |p|
  #     project = Project.find_by(external_id: p[:id].to_i, external_key: p[:key])
  #     if project.nil?
  #       # project needs a title
  #       Project.create(external_id: p[:id].to_i, external_key: p[:key])
  #     end
  #   end
  # end

end

app/controllers/projects_controller.rb
  class ProjectsController < ApplicationController

    before_action :set_project, except: [:new, :create, :index]


    def index
      @projects = Project.all
    end

    def new
      @project = Project.new
    end

    def show
      @concrete_templates = @project.concrete_issue_templates
      @issue_templates = IssueTemplate.all#.where.not(id: @concrete_templates.pluck(:issue_template_id))
    end

    def create
      project_id, project_title, existing = JiraConnector.check_for_project(params[:project][:external_key], current_user)
      if Project.find_by(external_id: project_id, external_key: params[:project][:external_key]).nil? && existing
        params[:project][:external_id] = project_id
        params[:project][:external_title] = project_title
        @project = Project.create(params.require(:project).permit(:external_key, :external_title, :external_id))
        if @project
          redirect_to '/projects', success: "Projekt erfolgreich erstellt!"
        end
      else
        redirect_to projects_path, danger: "Projekt konnte nicht in Jira gefunden werden!"
      end
    end

    def edit
    end

    def update
    end

    def destroy
      @project.destroy!
      redirect_to projects_path, success: "Das Projekt wurde unwiderruflich gelöscht!"
    end

    private

    def set_project
      @project = Project.find_by!(id: params[:id]) unless params[:id].blank?
    end

  end

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
  <div class="button-div">
    <%= button_to "Projekt erstellen", new_project_path, method: :get, class: "btn btn-info float-end mt-5" %>
  </div>
<div class="table-container">
  <table id="projects-table" class="table table-hover shadow rounded-custom">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Key</th>
        <th scope="col">Titel</th>
        <th scope="col">Aktionen</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |p| %>
        <tr>
          <td><%= p.id %></td>
          <td><%= p.external_key %></td>
          <td><%= p.external_title %></td>
          <td>
            <%= link_to(project_path(id: p.id),:class => 'btn action_btn') do %>
              <i class="fas fa-list"></i>
            <% end %>
            <%= link_to(project_path(id: p.id), :method => 'delete',:class => 'btn action_btn') do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<div class="title-container rounded-custom shadow">
  <h3>Projekt erstellen</h3>
</div>

<%= form_for @project do |f| %>

  <div class="container rounded-custom shadow">
    <%= f.label :title, "Projekt-Schlüssel" %>
    <%= f.text_field :external_key, class: "form-control project-key-field mt-3", required: true %>
    <div class="float-end mt-3">
      <%= button_tag(type: 'submit', class: "btn btn-info") do %>
        <span id="loader" class="spinner-border spinner-border-sm" role="status" style="display:none;"></span>
        <i id="prev_loader" class="fas fa-save"></i>
        Speichern
      <% end %>
    </div>
  </div>

<% end %>

app/views/projects/show.html.erb
<div class="table-container">
  <table id="projects-table" class="table table-hover shadow rounded-custom">
    <thead>
    <tr>
      <th scope="col">Titel</th>
      <th scope="col">Erstellt</th>
      <th scope="col">Aktionen</th>
    </tr>
    </thead>
    <tbody>
    <% @issue_templates.each do |it| %>
      <tr>
        <td><%= it.title %></td>
        <td>
          <% if it.created_for_project?(@project) %>
            <i class="fas fa-check"></i>
          <% else %>
            <i class="fas fa-times"></i>
          <% end %>
        </td>
        <td>
          <a class="btn action_btn <%= 'disabled' unless it.concrete_template_existing?(@project) %>" href="<%= concrete_issue_template_path(id: ConcreteIssueTemplate.find_by!(issue_template_id: it.id, project_id: @project.id).id) rescue '' %>">
            <i class="fas fa-upload"></i>
          </a>
          <% if it.concrete_template_existing?(@project) %>
            <%= link_to(edit_concrete_issue_template_path(id: ConcreteIssueTemplate.find_by!(issue_template_id: it.id, project_id: @project.id).id), :class => 'btn action_btn') do %>
              <i class="fas fa-edit"></i>
            <% end %>
          <% else %>
            <%= link_to(new_concrete_issue_template_path(issue_template_id: it.id, project_id: @project.id), :class => 'btn action_btn') do %>
              <i class="fas fa-list"></i>
            <% end %>
          <% end %>
          <a class="btn action_btn <%= 'disabled' unless it.concrete_template_existing?(@project) && !it.created_for_project?(@project)%>" href="<%= concrete_issue_template_path(id: ConcreteIssueTemplate.find_by!(issue_template_id: it.id, project_id: @project.id).id) rescue '' %>" data-method="delete">
            <i class="fas fa-trash-alt"></i>
          </a>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>