config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'projects#index'
  resources :projects
  resources :issue_templates do
    collection do
      post :add_attribute
    end
  end
  resources :sessions
  resources :users
  resources :concrete_issue_templates do
    collection do
      post :send_to_jira
    end
  end

  post 'first_login', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/models/issue_template.rb
class IssueTemplate < ApplicationRecord

  has_many :issue_template_attributes, dependent: :destroy
  has_many :concrete_issue_templates
  accepts_nested_attributes_for :issue_template_attributes



  # scope -> :assigned_attributes ()


  def created_for_project?(project)
    issue = project.concrete_issue_templates.where(issue_template_id: self.id).first
    issue && !issue.external_id.nil?
  end

  def concrete_template_existing?(project)
    project.concrete_issue_templates.where(issue_template_id: self.id).any?
  end

end

app/controllers/issue_templates_controller.rb
class IssueTemplatesController < ApplicationController

  before_action :set_issue_template, except: [:new, :create, :index]

  def index
    @templates = IssueTemplate.all
  end

  def new
    @issue_template = IssueTemplate.new
  end

  def create
    @issue_template = IssueTemplate.create(params.require(:issue_template).permit(:title))
    if @issue_template
      redirect_to edit_issue_template_path(id: @issue_template.id), success: "Erfolgreich erstellt!"
    end
  end

  def edit

  end

  def update
    if @issue_template.update(params.require(:issue_template).permit(:title, issue_template_attributes_attributes: [:field_value, :id, :optional_size]))
      redirect_to edit_issue_template_path(id: @issue_template.id), success: "Erfolgreich gespeichert!"
    end
  end

  def destroy
    @issue_template.destroy!
    redirect_to issue_templates_path, success: "Erfolgreich gelöscht!"
  end

  def add_attribute
    if params[:id].blank?
      @issue_template = IssueTemplate.create(title: params[:title])
    end
    IssueTemplateAttribute.create(issue_template_id: @issue_template.id, attribute_type: params[:attribute_type].to_i)
    render json: {id: @issue_template.id, location: "/issue_templates/#{@issue_template.id}/edit"}, success: "Erfolgreich erstellt!"
  end

  private

  def set_issue_template
    @issue_template = IssueTemplate.find_by!(id: params[:id]) unless params[:id].blank?
  end

end

app/views/issue_templates/edit.html.erb
<div class="title-container rounded-custom shadow">
  <h3>Vorlage bearbeiten</h3>
</div>

<%= form_for @issue_template, :html => { :'data-url' => "#{issue_template_path(id: @issue_template)}" } do |f| %>

  <div class="container rounded-custom shadow mh-70">
    <%= f.select(:issue_template_attributes,
                 IssueTemplateAttribute::ATTRIBUTE_TYPES.map { |ita| [I18n.t('template_type_'+ita.to_s), ita] },
                 {include_blank: "Feld auswählen"}, {class: 'form-select mt-3'}) %>
    <div class="float-end mt-3">
      <button type="button" class="add_attribute btn btn-info" data-id="<%= f.object.id %>">
        <i class="fas fa-check"></i>
        Hinzufügen
      </button>
      <%= button_tag(type: 'submit', class: "btn btn-info") do %>
        <span id="loader" class="spinner-border spinner-border-sm" role="status" style="display:none;"></span>
        <i id="prev_loader" class="fas fa-save"></i>
        Speichern
      <% end %>
    </div>
  </div>

  <div class="container rounded-custom shadow">
    <h5 class="pt-3">Titel</h5>
    <%= f.text_field :title, class: "form-control", required: true %>
  </div>

  <%= f.fields_for :issue_template_attributes do |ita| %>
    <div class="container rounded-custom shadow">
      <h5 class="pt-3"><%= I18n.t('template_type_'+ita.object.attribute_type.to_s) %></h5>
      <% if IssueTemplateAttribute::TYPE_KEY_VALUE == ita.object.attribute_type %>
        <%= ita.text_field :field_value, value: ita.object.field_value , class: "form-control" %>
      <% elsif IssueTemplateAttribute::TEXT_FIELD_ATTRIBUTES.include?(ita.object.attribute_type) %>
        <% if IssueTemplateAttribute::TYPE_CODEBLOCK == ita.object.attribute_type %>
          <div class="row col-12">
            <div class="col-10">
              <%= ita.label "Code" %>
              <%= ita.text_field :field_value, value: ita.object.field_value , class: "form-control" %>
            </div>
            <div class="col-2">
              <%= ita.label "Sprache" %>
              <%= ita.select :optional_size, [["Ruby", 0], ["HTML", 1], ["Python", 2]], {:prompt => 'Sprache wählen'}, {:class => "form-select"} %>
            </div>
          </div>
        <% else %>
          <%= ita.text_area :field_value, value: ita.object.field_value , class: "form-control" %>
        <% end %>
      <% elsif IssueTemplateAttribute::LIST_FIELD_ATTRIBUTES.include?(ita.object.attribute_type) %>
        <div class="row col-12">
          <div class="col-10">
            <%= ita.label "Titel" %>
            <%= ita.text_field :field_value, value: ita.object.field_value, class: "form-control" %>
          </div>
          <div class="col-2">
            <%= ita.label "Anzahl Punkte" %>
            <%= ita.number_field :optional_size, value: ita.object.optional_size, class: "form-control" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>


<% end %>

app/views/issue_templates/index.html.erb
<div class="button-div">
  <%= button_to "Template erstellen", new_issue_template_path, method: :get, class: "btn btn-info float-end mt-5" %>
</div>
<div class="table-container">
  <table id="issue_templates-table" class="table table-hover shadow rounded-custom">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Titel</th>
        <th scope="col">Aktionen</th>
      </tr>
    </thead>
    <tbody>
      <% @templates.each do |t| %>
        <tr>
          <td><%= t.id %></td>
          <td><%= t.title %></td>
          <td>
            <%= link_to(edit_issue_template_path(id: t.id),:class => 'btn action_btn') do %>
              <i class="fas fa-edit"></i>
            <% end %>
            <%= link_to(issue_template_path(id: t.id), :method => 'delete',:class => 'btn action_btn') do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/issue_templates/new.html.erb
<div class="title-container rounded-custom shadow">
  <h3>Vorlage erstellen</h3>
</div>

<%= form_for @issue_template do |f| %>

  <div class="container rounded-custom shadow mh-70">
    <%= f.select(:issue_template_attributes, IssueTemplateAttribute::ATTRIBUTE_TYPES.map { |ita| [I18n.t('template_type_'+ita.to_s), ita] }, {include_blank: "Feld auswählen"}, {class: 'form-select mt-3'}) %>
    <div class="float-end mt-3">
      <button type="button" class="add_attribute btn btn-info aj_btn" data-id="<%= f.object.id %>">
        <i class="fas fa-check"></i>
        Hinzufügen
      </button>
      <%= button_tag(type: 'submit', class: "btn btn-info") do %>
        <span id="loader" class="spinner-border spinner-border-sm" role="status" style="display:none;"></span>
        <i id="prev_loader" class="fas fa-save"></i>
        Speichern
      <% end %>
    </div>
  </div>

  <div class="container rounded-custom shadow">
    <h5 class="pt-3">Titel</h5>
    <%= f.text_field :title, class: "form-control", required: true %>
  </div>

<%end%>