config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'projects#index'
  resources :projects
  resources :issue_templates do
    collection do
      post :add_attribute
    end
  end
  resources :sessions
  resources :users
  resources :concrete_issue_templates do
    collection do
      post :send_to_jira
    end
  end

  post 'first_login', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid nav-container">
    <a class="navbar-brand" href="<%= root_path %>">Loopview</a>
    <% if logged_in? %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= projects_path %>">Projekte</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= issue_templates_path %>">Vorlagen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_path %>">Nutzer hinzufügen</a>
        </li>
      </ul>
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
          <span class="far fa-user p-2"></span>
          <strong><%= current_user.full_name %></strong>
        </a>
        <ul class="dropdown-menu text-small shadow mr-5" aria-labelledby="dropdownUser2">
          <li><a class="dropdown-item" href="/logout">Sign out</a></li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loopview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.3/fh-3.2.0/datatables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.3/fh-3.2.0/datatables.min.css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>" role="alert" style="position:fixed;width:100%;"><%= msg %></div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <% if current_user %>
      <div class="modal hide fade" id="modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modalLabel">API Token</h5>
            </div>
            <%= form_for current_user, class: "d-flex flex-column" do |f| %>
              <div class="modal-body">
                <p>Bitte gib zunächst deinen API-Token hier ein. Andernfalls wirst du nicht in der Lage sein, mit der JIRA-API zu kommunizieren!</p>
                <div class="form-floating">
                  <%= f.text_field :api_key, {class: "form-control", id:"floatingKey", placeholder: "Token"} %>
                  <%= f.label :api_key, "Token" %>
                </div>
              </div>
              <div class="modal-footer">
                <%= submit_tag "Speichern", class: "btn btn-primary" %>
              </div>
            <%end%>
          </div>
        </div>
      </div>
      <script type="text/javascript">
        $(window).on('load', function() {
          if ( <%= current_user.api_key.blank? %> ) {
            $('#modal').modal('show', {backdrop: 'static', keyboard: false});
          }
        });
      </script>
    <% end %>
  <script type="text/javascript">
      $(function() {
          setTimeout(function(){
              $('.alert').slideUp(500);
          }, 2500);
      });
  </script>
  </body>
</html>